# Generated by Django 5.2.17 on 2026-09-05 19:39

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TenantDirectory",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, primary_key=True, serialize=False)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("actor_id", models.CharField(max_length=64)),
                ("action", models.CharField(max_length=64)),
                ("resource_id", models.CharField(max_length=64)),
                ("correlation_id", models.CharField(blank=True, max_length=64)),
                ("details", models.JSONField(default=dict)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["organization_id", "created_at"], name="accounts_au_organiz_b99df7_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("email", models.EmailField(max_length=254)),
                ("role", models.CharField(max_length=16)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("accepted_at", models.DateTimeField(null=True)),
                (
                    "invited_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
                ("active", models.BooleanField(default=True)),
                ("retention_days", models.PositiveSmallIntegerField(default=400)),
                ("alerts_enabled", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("retention_days__in", [90, 180, 400])), name="org_retention_allowed"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportGrant",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("reason", models.CharField(max_length=500)),
                ("expires_at", models.DateTimeField()),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "support_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Membership",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("owner", "Owner"),
                            ("admin", "Admin"),
                            ("analyst", "Analyst"),
                            ("viewer", "Viewer"),
                            ("merchant", "Merchant"),
                        ],
                        max_length=16,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("store_id", models.UUIDField(null=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("organization_id", "user"), name="member_user_org_uniq")
                ],
            },
        ),
    ]
