# Generated by Django 5.2.17 on 2026-09-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_tenant_security"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantdirectory",
            name="erased_at",
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name="tenantdirectory",
            name="erasure_digest",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
