# Generated by Django 5.2.17 on 2026-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_privileges"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="store_id",
            field=models.UUIDField(null=True),
        ),
    ]
