# Generated by Django 5.2.17 on 2026-09-05 19:39

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AlertRoute",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("email", models.EmailField(max_length=254)),
                ("verified_at", models.DateTimeField(null=True)),
                ("active", models.BooleanField(default=True)),
                ("bounced_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("organization_id", "email"), name="alert_route_email_uniq")
                ],
            },
        ),
        migrations.CreateModel(
            name="Finding",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("mode", models.CharField(max_length=4)),
                ("finding_key", models.CharField(max_length=64, unique=True)),
                ("rule_code", models.CharField(max_length=6)),
                ("rule_version", models.CharField(max_length=32)),
                ("policy_version", models.PositiveIntegerField()),
                ("severity", models.CharField(max_length=16)),
                ("state", models.CharField(default="provisional", max_length=20)),
                ("identities", models.JSONField(default=list)),
                ("risk_amount_minor", models.BigIntegerField(null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("exponent", models.PositiveSmallIntegerField(default=2)),
                ("match_confidence", models.PositiveSmallIntegerField()),
                ("first_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("last_seen", models.DateTimeField(default=django.utils.timezone.now)),
                ("eligible_at", models.DateTimeField()),
                ("occurrence_count", models.PositiveIntegerField(default=0)),
                ("evidence", models.JSONField(default=dict)),
                ("evidence_hash", models.CharField(max_length=64)),
                ("suppressed_until", models.DateTimeField(null=True)),
                ("clean_since", models.DateTimeField(null=True)),
                ("clean_coverage_digest", models.CharField(blank=True, max_length=64)),
                ("resolved_at", models.DateTimeField(null=True)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="connectors.store")),
            ],
        ),
        migrations.CreateModel(
            name="Outbox",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("dedupe_key", models.CharField(max_length=255, unique=True)),
                ("task_type", models.CharField(max_length=32)),
                ("resource_id", models.UUIDField()),
                ("status", models.CharField(default="pending", max_length=16)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("available_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lease_until", models.DateTimeField(null=True)),
                ("provider_id", models.CharField(blank=True, max_length=255)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("delivery_state", models.CharField(blank=True, max_length=16)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["organization_id", "status", "available_at"], name="findings_ou_organiz_bdc4d0_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReconciliationRun",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("mode", models.CharField(max_length=4)),
                ("rule_version", models.CharField(max_length=32)),
                ("match_version", models.CharField(max_length=32)),
                ("policy_version", models.PositiveIntegerField()),
                ("input_digest", models.CharField(max_length=64)),
                ("evaluated_at", models.DateTimeField()),
                ("coverage", models.JSONField()),
                ("warnings", models.JSONField(default=list)),
                ("proposals", models.JSONField(default=list)),
                ("shadow", models.BooleanField(default=False)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="connectors.store")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FindingEvent",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("event_type", models.CharField(max_length=32)),
                ("actor_id", models.CharField(max_length=64)),
                ("previous_state", models.CharField(max_length=20)),
                ("new_state", models.CharField(max_length=20)),
                ("evidence", models.JSONField(default=dict)),
                ("note", models.CharField(blank=True, max_length=1000)),
                ("finding", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="findings.finding")),
                (
                    "run",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.PROTECT, to="findings.reconciliationrun"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="finding",
            index=models.Index(
                fields=["organization_id", "store", "state", "severity", "first_seen"],
                name="findings_fi_organiz_79f798_idx",
            ),
        ),
    ]
