# Generated by Django 5.2.17 on 2026-09-05 22:10

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("findings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailDelivery",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("provider_id", models.CharField(blank=True, max_length=255)),
                ("accepted_at", models.DateTimeField(null=True)),
                ("feedback_at", models.DateTimeField(null=True)),
                (
                    "event",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="findings.findingevent"
                    ),
                ),
                ("route", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="findings.alertroute")),
            ],
            options={
                "constraints": [models.UniqueConstraint(fields=("event", "route"), name="email_event_route_uniq")],
            },
        ),
    ]
