# Generated by Django 5.2.17 on 2026-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("findings", "0002_emaildelivery"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="digest_key",
            field=models.CharField(max_length=64, null=True, unique=True),
        ),
    ]
