# Generated by Django 5.2.17 on 2026-09-09 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_role_scope_constraints"),
        ("findings", "0003_emaildelivery_digest_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaildelivery",
            name="security_event",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.auditlog",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.UniqueConstraint(
                fields=("security_event", "route"),
                name="email_security_route_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="emaildelivery",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("digest_key__isnull", True),
                        ("event__isnull", False),
                        ("security_event__isnull", True),
                    ),
                    models.Q(
                        ("digest_key__isnull", True),
                        ("event__isnull", True),
                        ("security_event__isnull", False),
                    ),
                    models.Q(
                        ("digest_key__isnull", False),
                        ("event__isnull", True),
                        ("security_event__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="email_delivery_kind_one",
            ),
        ),
        migrations.RunSQL(
            """
            ALTER TABLE findings_emaildelivery
            ADD CONSTRAINT email_security_event_tenant_fk
            FOREIGN KEY (security_event_id, organization_id)
            REFERENCES accounts_auditlog(id, organization_id)
            DEFERRABLE INITIALLY DEFERRED;
            """,
            "ALTER TABLE findings_emaildelivery DROP CONSTRAINT email_security_event_tenant_fk;",
        ),
    ]
