# Generated by Django 5.2.17 on 2026-09-05 19:39

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("requested_by", models.PositiveBigIntegerField()),
                ("format", models.CharField(max_length=8)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("object_key", models.CharField(blank=True, max_length=255)),
                ("content_sha256", models.CharField(blank=True, max_length=64)),
                ("expires_at", models.DateTimeField()),
                (
                    "store",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="connectors.store"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
