# Generated by Django 5.2.17 on 2026-09-05 19:39

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("connectors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("principal", models.CharField(max_length=64)),
                ("route", models.CharField(max_length=200)),
                ("key", models.CharField(max_length=128)),
                ("request_hash", models.CharField(max_length=64)),
                ("response", models.JSONField()),
                ("response_status", models.PositiveSmallIntegerField()),
                ("expires_at", models.DateTimeField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "principal", "route", "key"), name="idempotency_scoped_key_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Observation",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("kind", models.CharField(max_length=24)),
                ("source_id", models.CharField(max_length=255)),
                ("revision", models.DateTimeField()),
                ("content_hash", models.CharField(max_length=64)),
                ("data", models.JSONField()),
                ("currency_table_version", models.CharField(max_length=64)),
                (
                    "connector",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="connectors.installation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Projection",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("kind", models.CharField(max_length=24)),
                ("source_id", models.CharField(max_length=255)),
                ("mode", models.CharField(max_length=4)),
                ("status", models.CharField(max_length=32)),
                ("amount_minor", models.BigIntegerField()),
                ("received_minor", models.BigIntegerField(default=0)),
                ("refunded_minor", models.BigIntegerField(default=0)),
                ("capturable_minor", models.BigIntegerField(default=0)),
                ("currency", models.CharField(max_length=3)),
                ("exponent", models.PositiveSmallIntegerField()),
                ("parent_id", models.CharField(blank=True, max_length=255)),
                ("transaction_id", models.CharField(blank=True, max_length=255)),
                ("pi_id", models.CharField(blank=True, db_index=True, max_length=255)),
                ("charge_id", models.CharField(blank=True, max_length=255)),
                ("session_id", models.CharField(blank=True, max_length=255)),
                ("method", models.CharField(blank=True, max_length=64)),
                ("capture_method", models.CharField(blank=True, max_length=32)),
                ("store_hint", models.CharField(blank=True, max_length=64)),
                ("order_hint", models.CharField(blank=True, db_index=True, max_length=20)),
                ("created_at_source", models.DateTimeField()),
                ("revision", models.DateTimeField()),
                ("paid_at", models.DateTimeField(null=True)),
                ("succeeded_at", models.DateTimeField(null=True)),
                (
                    "connector",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="connectors.installation"),
                ),
                (
                    "observation",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="ingestion.observation"),
                ),
                (
                    "store",
                    models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="connectors.store"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quota",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("bucket", models.CharField(max_length=128)),
                ("window", models.BigIntegerField()),
                ("count", models.PositiveIntegerField(default=0)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "bucket", "window"), name="quota_bucket_window_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("external_id", models.CharField(max_length=255)),
                ("body_hash", models.CharField(max_length=64)),
                ("kind", models.CharField(max_length=32)),
                ("source_id", models.CharField(blank=True, max_length=255)),
                ("event_type", models.CharField(blank=True, max_length=100)),
                ("event_created_at", models.DateTimeField(null=True)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("result", models.JSONField(default=dict)),
                (
                    "connector",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="connectors.installation"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cursor",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("object_class", models.CharField(max_length=32)),
                ("covered_from", models.DateTimeField(null=True)),
                ("covered_through", models.DateTimeField(null=True)),
                ("observed_at", models.DateTimeField(null=True)),
                ("complete", models.BooleanField(default=False)),
                ("scan_id", models.UUIDField(null=True)),
                ("scan_from", models.DateTimeField(null=True)),
                ("scan_through", models.DateTimeField(null=True)),
                ("next_page", models.PositiveIntegerField(default=1)),
                ("scan_failed", models.BooleanField(default=False)),
                (
                    "connector",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="connectors.installation"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("connector", "object_class"), name="cursor_class_uniq")
                ],
            },
        ),
        migrations.AddIndex(
            model_name="observation",
            index=models.Index(
                fields=["organization_id", "connector", "kind", "source_id"], name="ingestion_o_organiz_ea2fd1_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="observation",
            constraint=models.UniqueConstraint(
                fields=("connector", "kind", "source_id", "revision", "content_hash"), name="observation_revision_uniq"
            ),
        ),
        migrations.AddIndex(
            model_name="projection",
            index=models.Index(
                fields=["organization_id", "store", "mode", "kind", "revision"], name="ingestion_p_organiz_dc93f7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="projection",
            index=models.Index(fields=["connector", "kind", "parent_id"], name="ingestion_p_connect_b4a1b2_idx"),
        ),
        migrations.AddConstraint(
            model_name="projection",
            constraint=models.UniqueConstraint(
                fields=("connector", "kind", "source_id"), name="projection_namespace_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="projection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_minor__gte", 0),
                    ("capturable_minor__gte", 0),
                    ("received_minor__gte", 0),
                    ("refunded_minor__gte", 0),
                ),
                name="projection_nonnegative_amounts",
            ),
        ),
        migrations.AddConstraint(
            model_name="projection",
            constraint=models.CheckConstraint(
                condition=models.Q(("exponent__lte", 3)), name="projection_exponent_range"
            ),
        ),
        migrations.AddConstraint(
            model_name="projection",
            constraint=models.CheckConstraint(
                condition=models.Q(("currency__regex", "^[A-Z]{3}$")), name="projection_currency_format"
            ),
        ),
        migrations.AddConstraint(
            model_name="receipt",
            constraint=models.UniqueConstraint(
                fields=("connector", "external_id"), name="receipt_connector_external_uniq"
            ),
        ),
    ]
