# Generated by Django 5.2.17 on 2026-09-05 22:10

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scan",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("window_from", models.DateTimeField()),
                ("window_through", models.DateTimeField()),
                ("phase", models.PositiveSmallIntegerField(default=0)),
                ("provider_cursor", models.CharField(blank=True, max_length=255)),
                ("page_count", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="pending", max_length=16)),
                ("repair", models.BooleanField(default=False)),
                (
                    "connector",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="connectors.installation"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "pending")),
                        fields=("connector",),
                        name="scan_one_pending_connector",
                    )
                ],
            },
        ),
    ]
