# Generated by Django 5.2.17 on 2026-09-05 22:28

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("connectors", "0001_initial"),
        ("ingestion", "0002_scan"),
    ]

    operations = [
        migrations.CreateModel(
            name="BatchPage",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("scan_id", models.UUIDField()),
                ("page", models.PositiveIntegerField()),
                ("content_hash", models.CharField(max_length=64)),
                ("result", models.JSONField()),
                (
                    "connector",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="connectors.installation"),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(fields=("connector", "scan_id", "page"), name="batch_scan_page_uniq")
                ],
            },
        ),
    ]
