# Generated by Django 5.2.17 on 2026-09-05 19:39

import django.db.models.deletion
import django.utils.timezone
import modules.base
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Installation",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("kind", models.CharField(choices=[("woo", "Woo"), ("stripe", "Stripe")], max_length=10)),
                ("mode", models.CharField(max_length=4)),
                ("account_id", models.CharField(blank=True, max_length=255)),
                ("status", models.CharField(default="active", max_length=16)),
                ("destination_id", models.UUIDField(null=True, unique=True)),
                ("credential_ciphertext", models.JSONField(default=dict)),
                ("webhook_ciphertext", models.JSONField(default=dict)),
                ("token_expires_at", models.DateTimeField(null=True)),
                ("last_heartbeat_at", models.DateTimeField(null=True)),
                ("versions", models.JSONField(default=dict)),
                ("health", models.JSONField(default=dict)),
                ("last_error_code", models.CharField(blank=True, max_length=64)),
                ("next_api_at", models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PairingLocator",
            fields=[
                ("code_hash", models.CharField(max_length=64, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField()),
            ],
        ),
        migrations.CreateModel(
            name="ResourceLocator",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("kind", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="PublicKey",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("key_id", models.UUIDField(unique=True)),
                ("public_key", models.BinaryField(max_length=32)),
                ("expires_at", models.DateTimeField(null=True)),
                ("revoked_at", models.DateTimeField(null=True)),
                (
                    "installation",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="connectors.installation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Store",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("name", models.CharField(max_length=100)),
                ("hostname", models.CharField(max_length=253)),
                ("mode", models.CharField(choices=[("test", "Test"), ("live", "Live")], max_length=4)),
                ("active", models.BooleanField(default=True)),
                ("policy_version", models.PositiveIntegerField(default=1)),
                ("instant_grace_minutes", models.PositiveSmallIntegerField(default=10)),
                ("async_grace_minutes", models.PositiveSmallIntegerField(default=30)),
                ("refund_grace_minutes", models.PositiveSmallIntegerField(default=60)),
                ("freshness_minutes", models.PositiveSmallIntegerField(default=15)),
                ("disabled_rules", models.JSONField(default=list)),
                ("shadow_rules", models.BooleanField(default=False)),
                ("alerts_enabled", models.BooleanField(default=False)),
                ("dry_run_reviewed_at", models.DateTimeField(null=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("organization_id", "hostname", "mode"), name="store_hostname_mode_uniq"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PairingCode",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField()),
                ("used_at", models.DateTimeField(null=True)),
                ("issued_by", models.CharField(max_length=64)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="connectors.store")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OAuthState",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("state_hash", models.CharField(max_length=64, unique=True)),
                ("user_id", models.PositiveBigIntegerField()),
                ("session_hash", models.CharField(max_length=64)),
                ("expires_at", models.DateTimeField()),
                ("consumed_at", models.DateTimeField(null=True)),
                ("mode", models.CharField(max_length=4)),
                ("store", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="connectors.store")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="installation",
            name="store",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to="connectors.store"),
        ),
        migrations.CreateModel(
            name="StoreStripeLink",
            fields=[
                ("id", models.UUIDField(default=modules.base.uuid7, editable=False, primary_key=True, serialize=False)),
                ("organization_id", models.UUIDField(db_index=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ("updated_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("lock_version", models.PositiveIntegerField(default=0)),
                ("status", models.CharField(default="unverified", max_length=16)),
                ("owner_confirmed_at", models.DateTimeField(null=True)),
                ("merchant_confirmed_at", models.DateTimeField(null=True)),
                ("verified_payment_id", models.CharField(blank=True, max_length=255)),
                ("store", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="connectors.store")),
                (
                    "stripe",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to="connectors.installation"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="installation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("kind", "stripe"), ("status", "active")),
                fields=("organization_id", "account_id", "mode"),
                name="stripe_active_account_mode_uniq",
            ),
        ),
    ]
